### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by kttbalasuriyan** [bjssoftsolutions/serial_communication#12]
W/System.err(15863): java.io.FileNotFoundException: /proc/tty/drivers: open failed: EACCES (Permission denied)
W/System.err(15863): 	at libcore.io.IoBridge.open(IoBridge.java:574)
W/System.err(15863): 	at java.io.FileInputStream.<init>(FileInputStream.java:160)
W/System.err(15863): 	at java.io.FileInputStream.<init>(FileInputStream.java:115)
W/System.err(15863): 	at java.io.FileReader.<init>(FileReader.java:60)
W/System.err(15863): 	at android_serialport_api.SerialPortFinder.getDrivers(SerialPortFinder.java:65)
W/System.err(15863): 	at android_serialport_api.SerialPortFinder.getAllDevices(SerialPortFinder.java:87)
W/System.err(15863): 	at com.example.serial_communication.OpenCommunication.sendDeviceData(OpenCommunication.java:76)
W/System.err(15863): 	at com.example.serial_communication.SerialCommunicationPlugin.onMethodCall(SerialCommunicationPlugin.java:68)
W/System.err(15863): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
W/System.err(15863): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
W/System.err(15863): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
W/System.err(15863): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
W/System.err(15863): 	at android.os.Handler.handleCallback(Handler.java:978)
W/System.err(15863): 	at android.os.Handler.dispatchMessage(Handler.java:104)
W/System.err(15863): 	at android.os.Looper.loopOnce(Looper.java:238)
W/System.err(15863): 	at android.os.Looper.loop(Looper.java:357)
W/System.err(15863): 	at android.app.ActivityThread.main(ActivityThread.java:8090)
W/System.err(15863): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(15863): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
W/System.err(15863): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
W/System.err(15863): Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
W/System.err(15863): 	at libcore.io.Linux.open(Native Method)
W/System.err(15863): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
W/System.err(15863): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
W/System.err(15863): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
W/System.err(15863): 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7972)
W/System.err(15863): 	at libcore.io.IoBridge.open(IoBridge.java:560)

**Comment by momyuke** [comment]
Same here, is there any update for the permission issue? 
`/ample.jec_kiosk(30315): Compiler allocated 5085KB to compile void android.view.ViewRootImpl.performTraversals()
W/ample.jec_kiosk(30315): type=1400 audit(0.0:247151): avc: denied { read } for name="drivers" dev="proc" ino=4026531853 scontext=u:r:untrusted_app:s0:c248,c259,c512,c768 tcontext=u:object_r:proc_tty_drivers:s0 tclass=file permissive=0 app=com.example.jec_kiosk
W/System.err(30315): java.io.FileNotFoundException: /proc/tty/drivers: open failed: EACCES (Permission denied)
W/System.err(30315): 	at libcore.io.IoBridge.open(IoBridge.java:574)
W/System.err(30315): 	at java.io.FileInputStream.<init>(FileInputStream.java:160)
W/System.err(30315): 	at java.io.FileInputStream.<init>(FileInputStream.java:115)
W/System.err(30315): 	at java.io.FileReader.<init>(FileReader.java:60)
W/System.err(30315): 	at android_serialport_api.SerialPortFinder.getDrivers(SerialPortFinder.java:65)
W/System.err(30315): 	at android_serialport_api.SerialPortFinder.getAllDevices(SerialPortFinder.java:87)
W/System.err(30315): 	at com.example.serial_communication.OpenCommunication.sendDeviceData(OpenCommunication.java:76)
W/System.err(30315): 	at com.example.serial_communication.SerialCommunicationPlugin.onMethodCall(SerialCommunicationPlugin.java:68)
W/System.err(30315): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
W/System.err(30315): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
W/System.err(30315): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
W/System.err(30315): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
W/System.err(30315): 	at android.os.Handler.handleCallback(Handler.java:942)
W/System.err(30315): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err(30315): 	at android.os.Looper.loopOnce(Looper.java:211)
W/System.err(30315): 	at android.os.Looper.loop(Looper.java:300)
W/System.err(30315): 	at android.app.ActivityThread.main(ActivityThread.java:8152)
W/System.err(30315): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(30315): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
W/System.err(30315): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
W/System.err(30315): Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
W/System.err(30315): 	at libcore.io.Linux.open(Native Method)
W/System.err(30315): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
W/System.err(30315): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
W/System.err(30315): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
W/System.err(30315): 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8028)
W/System.err(30315): 	at libcore.io.IoBridge.open(IoBridge.java:560)
W/System.err(30315): 	... 19 more
D/hw-ProcessState(30315): Binder ioctl to enable oneway spam detection failed: Invalid argument`
