### ISSUE TITLE
couldn't find "libserial_port.so"

### ISSUE THREAD

**Issue by JosephhBh** [bjssoftsolutions/serial_communication#5]
I downloaded the example and when i try to open any port i get this messge : 
couldn't find "libserial_port.so" .

The .getAvailablePorts() returns :

D/SerialPort( 9491): Found new device: /dev/ttyXRUSB0
D/SerialPort( 9491): Found new device: /dev/ttyXRUSB3
D/SerialPort( 9491): Found new device: /dev/ttyXRUSB2
D/SerialPort( 9491): Found new device: /dev/ttyXRUSB1
D/SerialPort( 9491): Found new device: /dev/ttyS0
D/SerialPort( 9491): Found new device: /dev/ttyS4
D/SerialPort( 9491): Found new device: /dev/ttyFIQ0

**Comment by Halcooo** [comment]
Same bug here!

**Comment by AdaptingPro** [comment]
java.lang.UnsatisfiedLinkError: dlopen failed: library "libserial_port.so" not found

**Comment by eldhosekm** [comment]
libserial_port.so missing. 

Serial Port ：/dev/tty1WK3 D/SerialPortLog(12646): data format ：ascii D/SerialPortLog(12646): type：portmessages：Baud rate：50 flag bit ：0 Start the serial port E/AndroidRuntime(12646): FATAL EXCEPTION: main E/AndroidRuntime(12646): Process: com.example.serial_communication_example, PID: 12646 E/AndroidRuntime(12646): java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.serial_communication_example-ci-Sjh1A5B5_k5SUp0njtw==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.serial_communication_example-ci-Sjh1A5B5_k5SUp0njtw==/lib/arm64, /data/app/com.example.serial_communication_example-ci-Sjh1A5B5_k5SUp0njtw==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]] couldn't find "libserial_port.so" E/AndroidRuntime(12646): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1067) E/AndroidRuntime(12646): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1007)

**Comment by Halcooo** [comment]
@eldhosekm try using https://pub.dev/packages/flutter_libserialport

**Comment by eldhosekm** [comment]
> @eldhosekm try using https://pub.dev/packages/flutter_libserialport

i used this one but it giving me a permission denied error while getting all the available ports. my device architecture is arm64-v8a.
